baseurl = "/"
languageCode = "en-us"
title = "eltimn"

[pagination]
  pagerSize = 10

[params]
  Description = "The home of Tim Nelson"
  SelfIntro = "I'm Tim, a software developer. Currently focused on NixOS, Go, Kotlin, and HTMX."
  GithubID = "eltimn"
  BlueskyProfile = "https://bsky.app/profile/eltimn.bsky.social"

[menu]
  [[menu.main]]
    name = "post"
    weight = 0
    url = "/post"
